[package]
name = "merkle_tree_svm"
version = "0.1.0"
edition = "2021"

[dependencies]
fast-math = "0.1"
solana-hash = "2.1.13"
solana-sha256-hasher = "2.1.13"
bincode = "1.3"
solana-sdk = "2.1.10"
rand = "0.8"
serde ="1.0"
[dev-dependencies]
hex = "0.4.3"